### ISSUE TITLE
SPI on ISU0 doesn't work

### ISSUE THREAD

**Issue by felixdomke** [CodethinkLabs/mt3620-m4-drivers#1]
SPIMaster_Open(MT3620_UNIT_ISU0) will fail because it will set handle->id = 0. 0 is the legitimate ID for MT3620_UNIT_ISU0, but is rejected in https://github.com/CodethinkLabs/mt3620-m4-drivers/blob/9ca3b033b91dfabec7f905c9daa252f2d4ac1b4d/SPIMaster.c#L56 and some other places.

**Comment by aiden-ct** [comment]
Thanks. Fixed in 5a53f1924199ab40696fb36823f662c05175a34a.

**Comment by aiden-ct** [comment]
See also e1488eb6e17ab47fcb0a87f4f9c2d4ee5cefe2e1
