### ISSUE TITLE
Add Print#UART_vPrintf() 

### ISSUE THREAD

**Issue by kartben** [CodethinkLabs/mt3620-m4-drivers#10]
To ease wrapping of UART_Printf() calls, it'd be useful to have its variable argument lists variant.
```
int32_t UART_vPrintf(UART *handle, const char *format, va_list arg)
````

Happy to send a PR :)

**Comment by aiden-ct** [comment]
I'll take a look at this later today.

**Comment by kartben** [comment]
FWIW I have a working version and can send a patch if you're interested.

**Comment by aiden-ct** [comment]
You beat me to it! I've fixed a few niggles in my patch, but I'll add you as reviewer.

**Comment by aiden-ct** [comment]
Feel free to push your PR though.

**Comment by aiden-ct** [comment]
https://github.com/CodethinkLabs/mt3620-m4-drivers/pull/12 - I fixed some of the error handling too.
