### ISSUE TITLE
Mailbox API?

### ISSUE THREAD

**Issue by kartben** [CodethinkLabs/mt3620-m4-drivers#13]
Is there a plan to add APIs for interacting with the mailbox that can be used for inter-core communications?

**Comment by aiden-ct** [comment]
No specific plans to add support for the mailbox. I can have a look, but can't guarantee I'll have enough time to dedicate.

**Comment by aiden-ct** [comment]
By intercore, do you mean between the two M4s, or A7-M4?

**Comment by kartben** [comment]
All of the above, as both can be useful, but I'd personally care more about
A7<-->M4 to begin with.
