### ISSUE TITLE
SPIMaster_DMAEnable checks for wrong polarity in DMA start bit

### ISSUE THREAD

**Issue by felixdomke** [CodethinkLabs/mt3620-m4-drivers#2]
DMAx_START.STR bit is:

0: The DMA channel is stopped
1: The DMA channel is started and running

The code in SPIMaster_DMAEnable requires STR to be 1 (should be: 0) when disabling DMA:

https://github.com/CodethinkLabs/mt3620-m4-drivers/blob/9ca3b033b91dfabec7f905c9daa252f2d4ac1b4d/SPIMaster.c#L158

**Comment by aiden-ct** [comment]
Thanks for the review. Fixed in f67f190c4e29f2f5d7780062640edb51711bbbf0.
