### ISSUE TITLE
UART with Hardware Flow Control

### ISSUE THREAD

**Issue by breaultjean** [CodethinkLabs/mt3620-m4-drivers#28]
Hi,

It seems the UART driver as of today does not support the RTS/CTS hardware flow out of the box. We would like to _set_ the RTS pin when there is data in the TX send buffer and ensure it is _unset_ when there is no data in it. The idea is to interface with a RS485 transceiver in a non duplex scenario, similar to: 
<img width="142" alt="image" src="https://user-images.githubusercontent.com/54414354/156433862-38296ebb-21c4-46fd-8519-59721cffb769.png">

Is there a way to enable this scenario to your knowledge?

**What I tried so far:**
- Control the pin by using the GPIO driver, did not work.
- Set the auto_rts flag in the Uart_Open function.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/54414354/156434331-c5a5bdff-0ad8-444b-b2f8-5d8f61eb9431.png">

**More info on environment:**
- Azure Sphere SDK: 21.10.2.52856
- Sphere is the AES-MS-MT3620-M00-G
- Lib is at the latest from master (commit 0c4c772)

**Comment by ben-brewer-codethink** [comment]
This should be fixed in the latest commit.

**Comment by breaultjean** [comment]
Great! Thanks a lot.
