### ISSUE TITLE
GPIO's ConfigurePin() also needs to reset opposite configuration

### ISSUE THREAD

**Issue by dgarrett** [CodethinkLabs/mt3620-m4-drivers#3]
Currently ConfigurePin() in gpio.c sets the mask to oe_set if output or ie_set if input, but this results in a conflicting configuration if a pin is changed from output to input or vice versa.

ConfigurePin needs to first set the mask to oe_reset before setting ie_set, and ie_reset before setting oe_set to avoid a conflicting input/output configuration.

**Comment by dgarrett** [comment]
It might be better even to just leave ie alone (defaults to enabled) and only set/unset oe. It looks like messing with ie might conflict with how the Linux driver handles GPIOs for HighLevel apps.

**Comment by aiden-ct** [comment]
Thanks @dgarrett! Fixed in 3ed3666e. Re: "It might be better even to just leave ie alone (defaults to enabled) and only set/unset oe" - `ies` is input enable (not interrupt enable).
