### ISSUE TITLE
UART reading doesn't work if a callback isn't provided to UART_Open

### ISSUE THREAD

**Issue by dgarrett** [CodethinkLabs/mt3620-m4-drivers#4]
It looks like UART reading depends on the interrupt being enabled, but the interrupt is only enabled if a callback is provided to UART_Open. I would have expected to be able to call UART_Open with a NULL callback and still use the blocking UART_Read.

Instead UART_Read just blocks forever.

**Comment by aiden-ct** [comment]
Thanks. Fixed in d1557af7425a5da73a1b26dad243ddd49c67c79b.
