### ISSUE TITLE
GPIO driver doesn't support all GPIOs properly

### ISSUE THREAD

**Issue by dgarrett** [CodethinkLabs/mt3620-m4-drivers#7]
The GPIO driver only works correctly with GPIOs 0-23 and 41-48 (ADC block).

The other GPIOs that are associated with ISU blocks and I2S blocks don't work.

Can you please add support for GPIOs in ISU blocks and I2S blocks?

**Comment by aiden-ct** [comment]
@dgarrett - I've added support in the `aiden/extend-gpio` branch. The tests I added to the samples repo indicate something's not quite right. Will debug tomorrow, but have added my WIP to same name branches on samples and drivers, so you can test yourself.

**Comment by aiden-ct** [comment]
Note that to run the test with the Seed dev board, I've added some extra instructions to the README.md.

**Comment by aiden-ct** [comment]
Fixed in ebd74150ff60bbccd26cc394fe70e141a907b95a.
